<a href="https://colab.research.google.com/github/MacielDouglas/Senai_Python/blob/main/Aula_3_Senai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
# numpy é feito para alta precisão (seria possivel enviar foguete para lua com o numpy)


In [4]:
# random gera numeros aleatórios e estou pedindo para gerar duas linhas e tres colunas numeros aleatórios
# O objetivo é preencher ruidos ou numeros para teste, não importa quais seja esses dados
data = np.random.randn(2,3)
data


array([[-0.83686955, -1.58062064, -1.21116573],
       [ 0.24933367,  1.88158397, -0.83284563]])

In [ ]:
# ira multiplicar todos os que estão dentro do array por 10, pq todos tem uma proprieade escalar
data * 10

In [7]:
# é o mesmo que multiplicar por dois
data + data

array([[-1.67373909, -3.16124127, -2.42233147],
       [ 0.49866733,  3.76316794, -1.66569126]])

In [9]:
# para saber a forma do objeto usa o shape. O shape retorna o numero de linhas e comandos
data.shape

(2, 3)

In [10]:
#Para saber o tipo do objeto .dtype
data.dtype

dtype('float64')

Criar uma lista comum e transforma-la em um numpy

In [11]:
data1 = [6, 7.5, 8, 0, 1]
type(data1)

list

In [15]:
# SAi do objeto lista e vira um array
arr1 = np.array(data1)
type(arr1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Mas o que muda?
Na lista, ela está restrita a funções de lista.
No arr1, ela recebe as funções de numpy, ou seja recebe varias funções para manipulação de arrays, ou de algebra linear.
Se pode fazer muito mais com o array do que com uma lista.
Tambem é possível criar um array direto. 
Faremos isso no data2

In [16]:
#Criar uma lista aninhada
data2 = [[1, 2, 3, 4 ], [5, 6, 7, 8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
# ndarray pq é um array de duas junções e pode ter muito mais
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# Resultado será 2 pq é de duas dimenções, vamos comparar com arr1
arr2.ndim

2

In [19]:
# Resultado array de uma dimensão
arr1.ndim

1

A diferença abaixo dos dois array se refere a que o arr1 foi criao com ponto, ou seja ele é float.
Já o arr2 é int, pois foi criado sem ponto.

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
#duas colunas, tres linhas, duas camadas
#Essas duas matrizes é uma matriz só
# Técnicamente este objeto é um cubo.
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
# Esse objeto é como se fosse um cubo mágico
t1 = np.zeros((3, 3, 3))
t1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
# Uma matriz com três lados, ela tem comprimento, largura e profundidade
# uma foto tbm pode ser representada assim. Ela tem tres camadas de cores, rbg
t2 = np.random.randn(3, 3, 3)
t2

array([[[-0.21488359,  1.29961269,  1.39808092],
        [-0.40064307, -0.49623294,  0.02007321],
        [-0.12441367,  3.25685203,  0.32042351]],

       [[ 0.94761824,  1.70756404, -0.16966066],
        [ 1.66416045,  1.06655933, -0.36505613],
        [ 0.0844835 ,  1.0384038 , -0.49883802]],

       [[ 1.36568007, -0.87855225, -1.51165381],
        [ 2.13082911,  0.75743594, -0.29318955],
        [-0.13533522, -1.00286422,  0.21937227]]])

In [30]:
#Veremos as camadas da t2
#1ª Camada
t2[0]

array([[-0.21488359,  1.29961269,  1.39808092],
       [-0.40064307, -0.49623294,  0.02007321],
       [-0.12441367,  3.25685203,  0.32042351]])

In [31]:
# 2ª Camada, exel é em duas dimensões
t2[1]

array([[ 0.94761824,  1.70756404, -0.16966066],
       [ 1.66416045,  1.06655933, -0.36505613],
       [ 0.0844835 ,  1.0384038 , -0.49883802]])

In [32]:
#3º Camada
t2[2]

array([[ 1.36568007, -0.87855225, -1.51165381],
       [ 2.13082911,  0.75743594, -0.29318955],
       [-0.13533522, -1.00286422,  0.21937227]])

Se remover uma das camadas acima, O objeto vira um objeto de duas dimensões.

# Dtype
Um dtype é a forma como contruindo o objeto a memória ndarray e ele terá a capacidade de guardar informações.
Uma vez criado, podemos fazer conversoes coesirtivas mudanças em forma de dados 

In [33]:
# configuração np.float (entrada dos dados) consigo mostrar na máquina se a capacidade que por exemplo de um super nitendo ao ps5
#np.float é a precisão numérica, ao qual quero que np.array tenha spnitenou ou ps5
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [34]:
# A precisão dos inteiros são um pouco menor que a precisão dos floats.

arr2 = np.array([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [35]:
arr1.dtype

dtype('float64')

In [36]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1, 2, 3, 4, 5])


In [39]:
arr.dtype

dtype('int64')

In [40]:
#O arr foi criado com int32, e agora estou mudando para float64
# ele recebe um . que se refere a precisão decimal
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [41]:
float_arr.dtype

dtype('float64')

dtype, é o formato de precisão do dado dentro de np.array. Esse tipo de dado pode ser int, float, bool, objeto, lexico

In [42]:
#Forçanco que seja criado como um np.string
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [43]:
#Resultado S4, isso quer dizer que é uma string
numeric_strings.dtype

dtype('S4')

In [48]:
#Comando astype é para converter um objeto em outro. 
# No exemplo, estou convertendo em float, e não importa qual float
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [49]:
numeric_strings.astype(float).astype(int)

array([ 1, -9, 42])

In [50]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [52]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
empty_uint32 = np.empty(8, dtype = 'u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [55]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [57]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
1 / arr


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [60]:
arr ** 0.5 #raiz quadrada

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [61]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[5]

5

In [65]:
arr[5:8]

array([5, 6, 7])

In [66]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [68]:
arr[[2, 8]] =15
arr


array([ 0,  1, 15,  3,  4, 12, 12, 12, 15,  9])

In [69]:
arr[[8, 3, -1]]

array([15,  3,  9])

In [70]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [71]:
arr_slice[1] = 12345
arr

array([    0,     1,    15,     3,     4,    12, 12345,    12,    15,
           9])

In [72]:
arr_slice[:] = 64
arr

array([ 0,  1, 15,  3,  4, 64, 64, 64, 15,  9])

Tambem posso cria-lo como bool e converter para inteiro

In [73]:
arr = np.array([False, True, False, True, True, False])
arr

array([False,  True, False,  True,  True, False])

In [74]:
arr.dtype

dtype('bool')

In [75]:
arr.astype(int)

array([0, 1, 0, 1, 1, 0])

In [78]:
#Todos viram string
arr = np.array([0, .5, 8, .16, 'chuva'])
arr

array(['0', '0.5', '8', '0.16', 'chuva'], dtype='<U32')

In [81]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [82]:
arr2d[2]

array([7, 8, 9])

In [83]:
arr2d[0][2]

3

In [84]:
# É o mesmo que pegue a primeira linha ultima coluna
arr2d[0, 2]

3

In [98]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [102]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [103]:
arr3d[0] = old_values
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr = np.arange(10)

In [105]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [106]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [109]:
arr2d[1, :2]

array([4, 5])

In [110]:
arr2d[:2, 2]

array([3, 6])

In [111]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [112]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [113]:
arr2d[:2, 1:][:: -1]

array([[5, 6],
       [2, 3]])

In [114]:
arr_exercicio = np.random.randint(0, 10, 16).reshape((4, 4))
arr_exercicio

array([[3, 8, 8, 7],
       [9, 6, 4, 5],
       [3, 0, 1, 8],
       [9, 3, 5, 4]])

In [116]:
arr_exercicio[1:3, 1:3]

array([[6, 4],
       [0, 1]])

In [126]:
arr_exercicio[1:3, 3]

array([5, 8])

In [132]:
arr_exercicio[0, 2:]

array([8, 7])

In [188]:
arr_exercicio[2:, :2]

array([[3, 0],
       [9, 3]])

In [193]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [194]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [195]:
data = np.random.randn(7, 4)
data

array([[-0.23282119, -0.26050383,  2.30162209,  2.25336778],
       [-0.85748375,  0.4103921 , -0.20581639,  0.81051798],
       [ 1.27476131,  0.24480605,  0.77644166,  0.13071202],
       [ 0.31666887,  1.55549749, -0.73772963, -0.13335382],
       [ 0.10858893,  1.58433259,  0.36074652, -1.22397566],
       [-0.73544754,  0.12651763, -0.19173471, -0.91308015],
       [ 0.00904924,  0.50594776,  0.10267247,  2.64458897]])

In [196]:
data[[0, 6]]

array([[-0.23282119, -0.26050383,  2.30162209,  2.25336778],
       [ 0.00904924,  0.50594776,  0.10267247,  2.64458897]])

In [198]:
data[[True, False, False, False, False, False, True]]

array([[-0.23282119, -0.26050383,  2.30162209,  2.25336778],
       [ 0.00904924,  0.50594776,  0.10267247,  2.64458897]])

In [199]:
data[names == 'Bob']

array([[-0.23282119, -0.26050383,  2.30162209,  2.25336778],
       [ 0.31666887,  1.55549749, -0.73772963, -0.13335382]])

In [200]:
data[:, [True, False, False, True]]

array([[-0.23282119,  2.25336778],
       [-0.85748375,  0.81051798],
       [ 1.27476131,  0.13071202],
       [ 0.31666887, -0.13335382],
       [ 0.10858893, -1.22397566],
       [-0.73544754, -0.91308015],
       [ 0.00904924,  2.64458897]])

In [201]:
data[names == 'Bob', 2:]

array([[ 2.30162209,  2.25336778],
       [-0.73772963, -0.13335382]])

In [202]:
data[names == 'Bob', 3]

array([ 2.25336778, -0.13335382])

In [203]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [205]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [206]:
data[~(names == 'Bob')]

array([[-0.85748375,  0.4103921 , -0.20581639,  0.81051798],
       [ 1.27476131,  0.24480605,  0.77644166,  0.13071202],
       [ 0.10858893,  1.58433259,  0.36074652, -1.22397566],
       [-0.73544754,  0.12651763, -0.19173471, -0.91308015],
       [ 0.00904924,  0.50594776,  0.10267247,  2.64458897]])

In [207]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [208]:
data[mask]

array([[-0.23282119, -0.26050383,  2.30162209,  2.25336778],
       [ 1.27476131,  0.24480605,  0.77644166,  0.13071202],
       [ 0.31666887,  1.55549749, -0.73772963, -0.13335382],
       [ 0.10858893,  1.58433259,  0.36074652, -1.22397566]])

In [211]:
data[data < 0] = 0
data 

array([[0.        , 0.        , 2.30162209, 2.25336778],
       [0.        , 0.4103921 , 0.        , 0.81051798],
       [1.27476131, 0.24480605, 0.77644166, 0.13071202],
       [0.31666887, 1.55549749, 0.        , 0.        ],
       [0.10858893, 1.58433259, 0.36074652, 0.        ],
       [0.        , 0.12651763, 0.        , 0.        ],
       [0.00904924, 0.50594776, 0.10267247, 2.64458897]])

In [212]:
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [213]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [214]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [216]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [217]:
# Linhas e colunas = valores
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [219]:
#Estou pegando todas as linhas e ordenando como eu quero
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])