<a href="https://colab.research.google.com/github/MacielDouglas/Senai_Python/blob/main/Aula_2_Senai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Set é um tbm tipo de container de dados serve para operaçoes de pertinencia de valores mutuos e comparação de conjuntos.
# Esta relacionado com as propriedades dos índices da biblioteca panda, e serve para estudar únicas ou chaves primárias.
# Lembra operações com Join.

Set não aceita duplicidade.

In [18]:
# Set é um tbm tipo de container de dados serve para operaçoes de pertinencia de valores mutuos e comparação de conjuntos.
# Esta relacionado com as propriedades dos índices da biblioteca panda, e serve para estudar únicas ou chaves primárias.
# Lembra operações com Join.
set1 = {'Sorocaba', 'São Paulo', 'São Roque', 'Piedade', 'Campinas', 'Jiquiá', 'Perúibe', 'Campinas', 'São Paulo'}
set2 = {'São Paulo', 'Guarulhos', 'Guarulhos', 'Santana do Parnaíba', 'Aldeia da Serra', 'Osasco', 'Sorocaba'}

In [19]:
set1

{'Campinas',
 'Jiquiá',
 'Perúibe',
 'Piedade',
 'Sorocaba',
 'São Paulo',
 'São Roque'}

In [20]:
set2

{'Aldeia da Serra',
 'Guarulhos',
 'Osasco',
 'Santana do Parnaíba',
 'Sorocaba',
 'São Paulo'}

Segunda carascteristicas dos sets, contem funçoes e métodos.
Conjuntos: união, intersecção, junção.


In [21]:
set1.union(set2) # faz a união de tudo o que tem nos dois, removendo a duplicidade, faz reordenação


{'Aldeia da Serra',
 'Campinas',
 'Guarulhos',
 'Jiquiá',
 'Osasco',
 'Perúibe',
 'Piedade',
 'Santana do Parnaíba',
 'Sorocaba',
 'São Paulo',
 'São Roque'}

In [22]:
set2.difference(set1) # Diferença, tudo o que está em Set2 e não está em Set1

{'Aldeia da Serra', 'Guarulhos', 'Osasco', 'Santana do Parnaíba'}

In [23]:
set1.difference(set2)

{'Campinas', 'Jiquiá', 'Perúibe', 'Piedade', 'São Roque'}

In [24]:
set2.intersection(set1) # elementos que são comum nos dois.

{'Sorocaba', 'São Paulo'}

Os cod acima é praticamente uma teoria de join.

In [25]:
set2.add('Suzano')
set2

{'Aldeia da Serra',
 'Guarulhos',
 'Osasco',
 'Santana do Parnaíba',
 'Sorocaba',
 'Suzano',
 'São Paulo'}

In [26]:
set2.remove('Osasco')
set2

{'Aldeia da Serra',
 'Guarulhos',
 'Santana do Parnaíba',
 'Sorocaba',
 'Suzano',
 'São Paulo'}

# Dicionários

In [28]:
dic1 = {'Nome': 'Carlos',
         'Idade': 34,
         'Cidade': 'São Paulo',
         'Profissão': 'Jogador'}
dic1

{'Cidade': 'São Paulo', 'Idade': 34, 'Nome': 'Carlos', 'Profissão': 'Jogador'}

In [29]:
dic1['Nome']

'Carlos'

In [44]:
# Também aceita lisa
dic2 = {'Nome': ['Carlos', 'Paula'],
         'Idade': [34, 28],
         'Cidade': ['São Paulo' 'Valinhos'],
         'Profissão': ['Jogador', 'Professora']}
dic2

{'Cidade': ['São PauloValinhos'],
 'Idade': [34, 28],
 'Nome': ['Carlos', 'Paula'],
 'Profissão': ['Jogador', 'Professora']}

In [31]:
  dic2['Nome']

['Carlos', 'Paula']

In [32]:
dic2['Nome'][1]

'Paula'

In [46]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [5]:
# Array multdimensional, 4x4 4 arrays sobrepostos.
arr2 = np.array([[1, 2, 3, 4 ], 
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Pegando o arr1, chamando de pd.Series outro objeto com uma chave e um valor
dentro do Series, acrescentar um objeto chamado index. Esse indice gera uma chave. POde acessar por chave e valor.
Pandas focado em fazer um array de uma dimensão chamado series. O pandas foi feito para precessar estatistica e tres elementos para processar dados.
 cortes transversal, series de tempo e dados de painel(dataframes)

In [36]:
# Pegando o arr1, chamando de pd.Series outro objeto com uma chave e um valor
# dentro do Series, acrescentar um objeto chamado index. Esse indice gera uma chave. POde acessar por chave e valor.
# Pandas focado em fazer um array de uma dimensão chamado series. O pandas foi feito para precessar estatistica e tres elementos para processar dados.
# cortes transversal, series de tempo e dados de painel(dataframes)
series1 = pd.Series(arr1, index = [2000, 2001, 2002, 2003])
series1
series1[2001]

2

In [ ]:
data1 = pd.DataFrame(dic2)
data1

In [51]:
a = 100
b = 20

if (a < 100):
  print('Tudo OK')
else:
  print('Nok')

Nok


In [57]:
a = 20
b = 20

if (a >= 100):
  print('Tudo OK')
elif(a >= 80):
  print('Não é bom')
elif(a >= 60):
  print('Tá ficando feio.')
elif(a >= 50):
  print('Se segura')
elif(a >= 40):
  print('Melhor dar um jeito')
elif(a >= 30):
  print('vai estourar')
elif(a >=20):
  print('Presta atenção')
elif(a >= 10):
  print('Não vou falar mais nada.')
else:
  print('Nok')

Presta atenção


In [59]:
a = 1
b = 2

In [60]:
a == a

True

In [61]:
a == b

False

In [62]:
(a == a) & (a != b)

True

In [63]:
True & True

True

In [64]:
False & False

False

In [65]:
True & False

False

In [66]:
True | True

True

In [67]:
True | False

True

In [68]:
False | False

False

In [76]:
a = 1
b = 1

if (a > 0) | (b > 0):
  print('ok')
else:
  print('not')

ok


In [1]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
#enquanto n for menor ou igual a 10 continue fazendo o print
n = 0

while n <= 10:
  print(n)
  n += 1


0
1
2
3
4
5
6
7
8
9
10


In [12]:
for i in range(0, 10):
  if i == 5:
    pass
  else:
    print(i)

0
1
2
3
4
6
7
8
9


In [18]:

def juros(i, n, P):
  if (i > 1):
    print('O valor da taxa de juros não pode ser superior a 1')
    exit
  else:
    juros = P*(1+i)**n
    return(juros)


In [19]:
juros(i = 1.10, n = 2, P = 100)

O valor da taxa de juros não pode ser superior a 1


In [33]:
def media(x):
  if (len(x) == 0):
    print('Não poemos fazer média de um conjunto vazio')
    exit
  else:
    x = list(x)
    med = sum(x)/len(x)
    return med

In [35]:
media(x = [0, 0, 0, 0])

0.0

In [36]:
a = [0, 1, 2, 3, 4]

In [37]:
max(a) - min(a)

4

def normalizador, com uma referencia (x)
Essa função, que ela normaliza todos os elementos de um array, qual a principal posição dele, por uma referencia

In [40]:
import numpy as np

def normalizador(x):
  calc = np.array(x)
  norm = (calc.max() - calc) / calc.max()
  return norm

# É uma forma de fazer normalização.

In [41]:
normalizador(np.arange(15))

array([1.        , 0.92857143, 0.85714286, 0.78571429, 0.71428571,
       0.64285714, 0.57142857, 0.5       , 0.42857143, 0.35714286,
       0.28571429, 0.21428571, 0.14285714, 0.07142857, 0.        ])

In [46]:
def normalizador2(x):
  calc = np.array(x)
  norm2 = (calc.max() - calc) / (calc.max() - calc.min())
  return norm2

In [47]:
normalizador2(np.arange(15))

array([1.        , 0.92857143, 0.85714286, 0.78571429, 0.71428571,
       0.64285714, 0.57142857, 0.5       , 0.42857143, 0.35714286,
       0.28571429, 0.21428571, 0.14285714, 0.07142857, 0.        ])

In [48]:
def desvio_padrao(x):
  med = media(x)
  desv = sum(x - media(x))

In [61]:
x = [0, 1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 10, 13, 14, 15, 10, 15]
x = np.array(x)

In [62]:
sum((x - media(x))**2)/(len(x)- 1)

22.48692810457516

In [66]:
def variancia(x):
  x = np.array(x)
  var = sum((x-media(x))**2)/(len(x)-1)
  return var

In [67]:
variancia([0, 1, 2, 5, 6, 7, 10, 12, 13, 15, 19])

37.763636363636365

In [69]:
def desvio(x):
  x = np.array(x)
  desvio = np.sqrt(sum((x-media(x))**2)/(len(x)-1))
  return(desvio)

In [70]:
desvio([0, 1, 2, 5, 6, 7, 10, 12, 13, 15, 19])

6.145212475060269

In [71]:
def amplitude(x):
  ampl = max(x) - min(x)
  return ampl

In [72]:
amplitude([1, 2, 3, 10])

9

In [73]:
# calculo de juros em 20 meses
i = .10
n = np.arange(0, 20)
p = 100

In [74]:
p*(1+i)**n

array([100.        , 110.        , 121.        , 133.1       ,
       146.41      , 161.051     , 177.1561    , 194.87171   ,
       214.358881  , 235.7947691 , 259.37424601, 285.31167061,
       313.84283767, 345.22712144, 379.74983358, 417.72481694,
       459.49729864, 505.4470285 , 555.99173135, 611.59090448])

In [76]:
#Emprestimo parcela d 1500 com juros de 5% em 20 meses
pmt = 1500
i = 0.05
n = np.arange(20)

In [77]:
# quanto pagaria para o banco todas as prestações
pmt*20

30000

In [78]:
#   quanto pagaria hoje descontando os juros
pmt/((1+i)**n)

array([1500.        , 1428.57142857, 1360.54421769, 1295.7563978 ,
       1234.05371219, 1175.2892497 , 1119.32309495, 1066.0219952 ,
       1015.25904304,  966.91337433,  920.86988031,  877.01893363,
        835.25612727,  795.48202597,  757.60192949,  721.52564714,
        687.16728299,  654.44503142,  623.2809823 ,  593.60093552])

In [79]:
# quanto devo para o banco
sum(pmt/((1+i)**n))

19627.98128950047

In [80]:
#Quanto estou pagando de juros
pmt*20 - sum(pmt/((1+i)**n))

10372.018710499531