<a href="https://colab.research.google.com/github/MacielDouglas/Senai_Python/blob/main/Aula_05_Senai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop(['c'])
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop(['b', 'd'])

a    0.0
c    2.0
e    4.0
dtype: float64

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['two'], axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(['two', 'four'], axis = "columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
obj.drop('c', inplace = True, errors="ignore")

In [ ]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj = pd.Series(np.arange(4.),
                index = list('abcd'))
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['b']

1.0

In [ ]:
obj[1]

1.0

In [ ]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [ ]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [ ]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [ ]:
obj['b' : 'c']

b    1.0
c    2.0
dtype: float64

In [ ]:
obj['b' : 'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [ ]:
data.two

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [ ]:
data[['two', 'three']]

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

#qual dos objetos retornam um padas dataframe
* **data[ [ 'two', "three" ] ]**
* **data[ [ 'two' ] ]**
* ~data[ 'two' ]~
* ~data.two~



In [ ]:
type(data.two)

pandas.core.series.Series

In [ ]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

#loc e iloc
Formas de acessar as informaçoes dentro do data frame, sao as colunas

ou fala a apartir do nome dos eixos de (indice e colunas) eu falo pelas posições.
Loc e a Iloc são chaves de acesso a chave de valor posso falar por meio de indices e colunas oupor  meio dos nomes.


In [ ]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [ ]:
data.loc[: 'Utah', ['two']]

two
Ohio        0
Colorado    5
Utah        9

In [ ]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
# consultas por meio de indices quebrados
ser = pd.Series(np.arange(3.))

In [ ]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [ ]:
ser2 = pd.Series(np.arange(3.), index = list('abc'))

In [ ]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [ ]:
ser2[-1]

2.0

In [ ]:
ser[:1]

0    0.0
dtype: float64

In [ ]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [ ]:
ser2[-3]

0.0

In [ ]:
ser2[-1]

2.0

In [ ]:
ser[:1]

0    0.0
dtype: float64

In [ ]:
ser.loc[1]

1.0

In [ ]:
ser.iloc[:1]

0    0.0
dtype: float64

Alinhamento e matemática com DataFrames

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5,], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                   columns = list('bcd'),
                   index = ['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                   columns = list('bde'),
                   index = ['Utah', 'Ohio', 'Texas', 'Oregonn'])

In [ ]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregonn   NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [ ]:
df1

A
0  1
1  2

In [ ]:
df2

B
0  3
1  4

In [ ]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns = list('abcde'))

In [ ]:
df2.loc[1, 'b'] = np.nan

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(0.01)

a         b         c         d
0      inf  0.010000  0.005000  0.003333
1  0.00250  0.002000  0.001667  0.001429
2  0.00125  0.001111  0.001000  0.000909

In [ ]:
df1.reindex(columns = df2.columns, fill_value =0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [ ]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape(4, 3), 
                     columns = list('bde'),
                     index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [ ]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [ ]:
series2 = pd.Series(range(3), index = ['b', 'd', 'e'])

In [ ]:
frame + series2

b   d   e
Utah    0   2   4
Ohio    3   5   7
Texas   6   8  10
Oregon  9  11  13

In [ ]:
series3 = frame['d']
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [ ]:
frame.sub(series3, axis = 'index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3),
                     columns = list('bde'),
                     index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
frame

b         d         e
Utah    0.741601 -1.171299  0.735783
Ohio    1.567575  0.780326  0.184581
Texas   1.192900 -1.645293 -0.591702
Oregon  0.506548 -1.041624 -2.017224

In [ ]:
np.abs(frame)

b         d         e
Utah    0.741601  1.171299  0.735783
Ohio    1.567575  0.780326  0.184581
Texas   1.192900  1.645293  0.591702
Oregon  0.506548  1.041624  2.017224

In [ ]:
f = lambda x: x.max() - x.min()

In [ ]:
frame.apply(f, axis = "index")

b    1.061027
d    2.425618
e    2.753007
dtype: float64

In [ ]:
def f(x):
  return pd.Series([x.min(), x.max(), x.max() - x.min(), x.mean(), x.std(), len(x)], index = ['min', 'max', 'range', "mean", 'std', 'count'])

In [ ]:
frame.apply(f, axis = "columns")

min       max     range      mean       std  count
Utah   -1.171299  0.741601  1.912900  0.102029  1.102738    3.0
Ohio    0.184581  1.567575  1.382994  0.844160  0.693703    3.0
Texas  -1.645293  1.192900  2.838193 -0.348032  1.434701    3.0
Oregon -2.017224  0.506548  2.523772 -0.850767  1.272665    3.0

In [ ]:
frame.describe()

b         d         e
count  4.000000  4.000000  4.000000
mean   1.002156 -0.769472 -0.422140
std    0.472440  1.065280  1.194702
min    0.506548 -1.645293 -2.017224
25%    0.682838 -1.289797 -0.948083
50%    0.967251 -1.106461 -0.203561
75%    1.286569 -0.586137  0.322382
max    1.567575  0.780326  0.735783

In [ ]:
format = lambda x: '% .2f' % x

In [ ]:
frame.applymap(format)

b      d      e
Utah     0.74  -1.17   0.74
Ohio     1.57   0.78   0.18
Texas    1.19  -1.65  -0.59
Oregon   0.51  -1.04  -2.02

In [ ]:
frame['e'].map(format)

Utah       0.74
Ohio       0.18
Texas     -0.59
Oregon    -2.02
Name: e, dtype: object

In [ ]:
obj = pd.Series(range(4), index = list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
frame = pd.DataFrame(np.arange(8.).reshape((2, 4)),
                     index = ['three', 'one'],
                     columns = ['d', 'a', 'b', 'c'])
frame

d    a    b    c
three  0.0  1.0  2.0  3.0
one    4.0  5.0  6.0  7.0

In [ ]:
frame.sort_index()

d    a    b    c
one    4.0  5.0  6.0  7.0
three  0.0  1.0  2.0  3.0

In [ ]:
frame.sort_index(axis=1)

a    b    c    d
three  1.0  2.0  3.0  0.0
one    5.0  6.0  7.0  4.0

In [ ]:
frame.sort_index(axis = 1, ascending = False)

d    c    b    a
three  0.0  3.0  2.0  1.0
one    4.0  7.0  6.0  5.0

In [ ]:
frame = pd.DataFrame({'b': [4, 7, -3, 2],
                      'a': [0, 1, 0, 1]})

In [ ]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [ ]:
frame.sort_values(by = ['a', 'b'], ascending = False)

b  a
1  7  1
3  2  1
0  4  0
2 -3  0

In [ ]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [ ]:
obj.rank(ascending = False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [ ]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [ ]:
obj.rank(ascending= False, method = "max")

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [ ]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2],
                      'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [ ]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [ ]:
df = pd.DataFrame([[1.4, np.nan],
                   [7.1, -4.5],
                   [np.nan, np.nan],
                   [0.75, -1.3]],
                  index = ['a', 'b', 'c', 'd'], 
                  columns = ['one', 'two']
                )
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [ ]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [ ]:
df.mean(axis = "columns", skipna = True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [ ]:
df.idxmax()

one    b
two    d
dtype: object

In [ ]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [ ]:
# Usando na comparações de ações
price = pd.read_pickle("yahoo_price.pkl")
volume = pd.read_pickle("yahoo_volume.pkl")

In [ ]:
# mostraria as açoes das empresas selecionadas
price

#Funçoes especificas para estatisticas / finanças

In [ ]:
# .pct_change() mudança percentual de um dia para o outro
price.pct_change()

In [ ]:
# returns para ver as ultimas entradas da base de dados
returns = price.pct_change()
returns.tail()

In [ ]:
#Calcular os retornos de uma empres em comparação com outra.
# No caso retornos da Microsoft em comparação com os da IBM
returns['MSFT'].corr(returns['IBM'])

#tanto faz a ordem o resultado é o mesmo
returns['IBM'].corr(returns['MSFT'])

In [ ]:
# O mesmo do acima, mas feito de uma forma diferente
# Os retornos da Microsoft em correlação aos da IBM
returns.MSFT.corr(returns.IBM)

In [ ]:
 # Uma correlação de tdo mundo contra tdo mundo, gera uma matriz quadrada.
 returns.corr()
 # Os resultados que aparece de 1.0000 se refere a empresa contra a própria empresa



In [ ]:
#Podemos ver uma matriz de co-variação
returns.cov()

In [ ]:
#Utilizando apenas em relação a IBM
returns.corrwith(returns.IBM)

UNIQUE O SELECT distinct DO SQL

In [3]:
obj = pd.Series(['a', 'c', 'd', 'a', 'a', 'a', 'b', 'b', 'c', 'c'])

In [4]:
#select distinct
uniques = obj.unique()
uniques

array(['a', 'c', 'd', 'b'], dtype=object)

In [6]:
# Select distinct counts
obj.value_counts()

a    4
c    3
b    2
d    1
dtype: int64