<a href="https://colab.research.google.com/github/MacielDouglas/Senai_Python/blob/main/Compreendendo_NumPy_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [14]:
zero_array = np.zeros(shape = (5, 3, 6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [15]:
print(zero_array.shape)
print(zero_array.size)
print(zero_array.ndim)

(5, 3, 6)
90
3


In [9]:
zero_dez = np.arange(10)
print(zero_dez)

pula_dois = np.arange(3, 15, 2)
print(pula_dois)

[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13]


In [13]:
array_linear = np.linspace(0, 100, num = 20, endpoint = False, retstep=True)
print(array_linear)

(array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.]), 5.0)


In [19]:
a = np.array([1, 2, 3])

print(a.max())
print(a.min())
print(a.mean())
print(a.sum())

3
1
2.0
6


In [31]:
#Gerando amostras aleatórias
from numpy.random import default_rng

rng = default_rng()
aleatorio = rng.integers(10, size=(2, 4))
print(aleatorio)

[[6 5 5 4]
 [7 2 6 7]]


Diferença entre Arrays e Listas:

In [33]:
a = np.array([1, 3, 4, 5, 6, 7, 8])
print("Essa é o array 'a': ", a)
print('Esse é tipo "a":', type(a))
print('--------------------------------')
lista_a = [1, 3, 4, 5, 6, 7, 8, 9]
print("Essa é a 'lista_a':", lista_a)
print("Esse é tipo de 'lista_a':", type(lista_a))

Essa é o array 'a':  [1 3 4 5 6 7 8]
Esse é tipo "a": <class 'numpy.ndarray'>
--------------------------------
Essa é a 'lista_a': [1, 3, 4, 5, 6, 7, 8, 9]
Esse é tipo de 'lista_a': <class 'list'>


In [37]:
# Arrays não permitem tipos de dados distintos, Ele fará conversão
c = np.array([1, 'Marcelo', 2, 4, 5, 6, 7, 8, 9, ])
print(c)
print(type(c[0]))
d = np.array([1, 4, 6, 8, 45, 76, 1000])
print(d)
print(type(d[0]))

['1' 'Marcelo' '2' '4' '5' '6' '7' '8' '9']
<class 'numpy.str_'>
[   1    4    6    8   45   76 1000]
<class 'numpy.int64'>


In [40]:
# Em listas sim
list_c = [1, 'Marcelo', 2, 4, 5, 6, 7, 8, 9, ]
print(list_c)
print(type(list_c[0]))
print(type(list_c[1]))

[1, 'Marcelo', 2, 4, 5, 6, 7, 8, 9]
<class 'int'>
<class 'str'>
